version: '2'
services:
  jhipstersampleapplication9-app:
    image: jhipstersampleapplication9
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipstersampleapplication9-postgresql:5432/jhipsterSampleApplication9
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipstersampleapplication9-postgresql:
    extends:
      file: postgresql.yml
      service: jhipstersampleapplication9-postgresql
